name: Publish Github

on:
  workflow_dispatch:
  workflow_call:

concurrency:
  group: publish-github-${{ github.ref }}
  cancel-in-progress: true

jobs:
  generate_id:
    name: Generate ID of release
    runs-on: ubuntu-latest
    outputs:
      formatted_date: ${{ steps.date.outputs.formatted_date }}
    steps:
      - name: Get current date
        id: date
        run: echo "formatted_date=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_OUTPUT

  publish:
    name: ${{ matrix.cuda_short_version }}
    needs: [generate_id]
    strategy:
      fail-fast: false
      matrix:
        torch_version:
          - "2.3.1"
          - "2.4.0"
          - "2.4.1"
          - "2.5.0"
          - "2.5.1"
        cuda_short_version:
          - "121"
          - "124"
        exclude:
          - torch_version: "2.3.1"
            cuda_short_version: "124"
          - torch_version: "2.5.0"
            python: "3.8"
          - torch_version: "2.5.1"
            python: "3.8"
    permissions:
      contents: write

    uses: ./.github/workflows/release.yml
    with:
      torch_version: ${{ matrix.torch_version }}
      cuda_short_version: ${{ matrix.cuda_short_version }}
      release_tag: "torch${{ matrix.torch_version }}_cu${{ matrix.cuda_short_version }}"
